Improve startup_checks.py
Deprecate startup_checks.sh.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -15,6 +15,7 @@ concurrency:
 # # https://github.com/actions/runner-images/tree/main
 jobs:
   Sanity_Checks:
+    name: Sanity Checks
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -26,7 +27,7 @@ jobs:
           docker run --mount type=bind,src=.,dst=/server
           -e GIT_REF=origin/${{ github.event.pull_request.base.ref }}
           --rm ghcr.io/${{ github.repository_owner }}/devtools:ubuntu
-          /bin/bash -c '/server/tools/ci/main.sh'
+          /bin/bash -c '/server/tools/ci/sanity_checks/main.sh'
 
       - name: Summarize checks
         id: summarize_checks
@@ -35,30 +36,38 @@ jobs:
           echo "## Sanity Check Results" >> $GITHUB_STEP_SUMMARY
           found_issues=false
           for check_file in ./*_checks.md; do
-              if [[ -f "$check_file" && -s "$check_file" ]]; then
-                  found_issues=true
-                  check_name=$(basename "$check_file" _checks.md | sed 's/.*/\u&/; s/_\(.\)/ \u\1/g')
-                  echo "### :warning: ${check_name} Checks Failed" >> $GITHUB_STEP_SUMMARY
-                  tr -d '\r' < "$check_file" >> $GITHUB_STEP_SUMMARY
-                  echo "" >> $GITHUB_STEP_SUMMARY
+              if [[ -f "$check_file" ]]; then
+                check_name=$(basename "$check_file" _checks.md | sed 's/.*/\u&/; s/_\(.\)/ \u\1/g')
+                if [[ -s "$check_file" ]]; then
+                    found_issues=true
+                    echo "### :x: ${check_name} Checks Failed" >> $GITHUB_STEP_SUMMARY
+                    tr -d '\r' < "$check_file" >> $GITHUB_STEP_SUMMARY
+                    echo "" >> $GITHUB_STEP_SUMMARY
+                else
+                    echo "### :heavy_check_mark: ${check_name} Checks Passed" >> $GITHUB_STEP_SUMMARY
+                    echo "" >> $GITHUB_STEP_SUMMARY
+                fi
               fi
           done
           for check_file in ./*_checks.txt; do
-              if [[ -f "$check_file" && -s "$check_file" ]]; then
-                  found_issues=true
-                  check_name=$(basename "$check_file" _checks.txt | sed 's/.*/\u&/; s/_\(.\)/ \u\1/g')
-                  echo "### :warning: ${check_name} Checks Failed" >> $GITHUB_STEP_SUMMARY
-                  echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
-                  tr -d '\r' < "$check_file" >> $GITHUB_STEP_SUMMARY
-                  echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
-                  echo "" >> $GITHUB_STEP_SUMMARY
+              if [[ -f "$check_file" ]]; then
+                check_name=$(basename "$check_file" _checks.txt | sed 's/.*/\u&/; s/_\(.\)/ \u\1/g')
+                if [[ -s "$check_file" ]]; then
+                    found_issues=true
+                    echo "### :x: ${check_name} Checks Failed" >> $GITHUB_STEP_SUMMARY
+                    echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+                    tr -d '\r' < "$check_file" >> $GITHUB_STEP_SUMMARY
+                    echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+                    echo "" >> $GITHUB_STEP_SUMMARY
+                else
+                    echo "### :heavy_check_mark: ${check_name} Checks Passed" >> $GITHUB_STEP_SUMMARY
+                    echo "" >> $GITHUB_STEP_SUMMARY
+                fi
               fi
           done
           if [[ "$found_issues" == "false" ]]; then
-              if [[ "${{ steps.run_checks.outcome }}" == "success" ]]; then
-                  echo ":heavy_check_mark: All checks passed." >> $GITHUB_STEP_SUMMARY
-              else
-                  echo ":x: Sanity check failed, but no specific output files were found/populated." >> $GITHUB_STEP_SUMMARY
+              if [[ "${{ steps.run_checks.outcome }}" != "success" ]]; then
+                  echo "### :x: Sanity check failed, but no specific output files were found/populated." >> $GITHUB_STEP_SUMMARY
                   echo "Check the logs of the 'Run tests' step for details." >> $GITHUB_STEP_SUMMARY
                   found_issues=true
               fi
@@ -71,6 +80,7 @@ jobs:
           exit 1
 
   Lua_Language_server:
+    name: Lua Language Server
     needs: Sanity_Checks
     runs-on: ubuntu-latest
     steps:
@@ -82,7 +92,7 @@ jobs:
         run: >
           docker run --mount type=bind,src=.,dst=/server
           --rm ghcr.io/${{ github.repository_owner }}/devtools:ubuntu
-          /bin/bash -c 'python3 tools/ci/lua_lang_server.py'
+          /bin/bash -c 'python ./tools/ci/lua_lang_server.py'
 
       - name: Summarize run
         id: summarize_run
@@ -93,7 +103,7 @@ jobs:
           check_file=lua_lang_errors.txt
           if [[ -f "$check_file" && -s "$check_file" ]]; then
               found_issues=true
-              echo "### :warning: Run Failed" >> $GITHUB_STEP_SUMMARY
+              echo "### :x: Run Failed" >> $GITHUB_STEP_SUMMARY
               echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
               tr -d '\r' < "$check_file" >> $GITHUB_STEP_SUMMARY
               echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
@@ -101,9 +111,9 @@ jobs:
           fi
           if [[ "$found_issues" == "false" ]]; then
               if [[ "${{ steps.run_lls.outcome }}" == "success" ]]; then
-                  echo ":heavy_check_mark: All checks passed." >> $GITHUB_STEP_SUMMARY
+                  echo "### :heavy_check_mark: All checks passed." >> $GITHUB_STEP_SUMMARY
               else
-                  echo ":x: Lua Language Server had errors, but no specific output was found." >> $GITHUB_STEP_SUMMARY
+                  echo "### :x: Lua Language Server had errors, but no specific output was found." >> $GITHUB_STEP_SUMMARY
                   echo "Check the logs of the 'Run Lua Language Server' step for details." >> $GITHUB_STEP_SUMMARY
                   found_issues=true
               fi
@@ -117,6 +127,7 @@ jobs:
 
   # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
   Build_Linux:
+    name: Build Linux
     needs: Sanity_Checks
     runs-on: ubuntu-latest
     env:
@@ -234,9 +245,10 @@ jobs:
           path: ${{ format('{0}/{1}.tar', runner.temp, env.artifact_name) }}
 
   Startup_Checks_Linux:
+    name: Startup Checks
     runs-on: ubuntu-latest
     needs: Build_Linux
-    if: ${{ !cancelled() }}
+    if: ${{ !cancelled() && needs.Build_Linux.result == 'success' }}
     env:
       MARIADB_DATABASE: xidb
       MARIADB_USER: xiadmin
@@ -272,7 +284,7 @@ jobs:
         env:
           PR_NUMBER: ${{ github.event.pull_request.number || github.event.number }}
         run: |
-          IMAGE_TO_RUN="ghcr.io/${{ github.repository }}:pr-${PR_NUMBER}-gcc14"
+          IMAGE_TO_RUN="ghcr.io/${{ github.repository }}:pr-${{ env.PR_NUMBER }}-gcc14"
           docker load --input ${{ runner.temp }}/ubuntu_image_Debug.tar
 
           echo "Attempting to run image: $IMAGE_TO_RUN"
@@ -282,31 +294,28 @@ jobs:
 
           docker run -dt \
             --name test-server \
+            --user root \
             --network ${{ job.services.database.network }} \
-            --mount type=bind,src=.,dst=/server/log \
+            --mount type=bind,src=./log,dst=/server/log \
+            --mount type=bind,src=./losmeshes,dst=/server/losmeshes \
+            --mount type=bind,src=./navmeshes,dst=/server/navmeshes \
             --env XI_NETWORK_SQL_HOST=database \
+            --env XI_NETWORK_SQL_PORT=3306 \
             --env XI_NETWORK_SQL_DATABASE=${{ env.MARIADB_DATABASE }} \
             --env XI_NETWORK_SQL_LOGIN=${{ env.MARIADB_USER }} \
             --env XI_NETWORK_SQL_PASSWORD=${{ env.MARIADB_PASSWORD }} \
-            "$IMAGE_TO_RUN"
+          "$IMAGE_TO_RUN"
 
       - name: Initialize database
         id: init_db
         run: docker exec test-server /bin/bash -c 'python ./tools/dbtool.py update'
 
-      - name: Start server
-        run: docker exec test-server /bin/bash -c './tools/ci/start_server.sh' && sleep 300
+      - name: Run tests
+        id: tests
+        run: docker exec test-server /bin/bash -c 'python -m tools.ci.startup_checks'
 
-      - name: Create test character
-        run: docker exec test-server /bin/bash -c './tools/ci/create_test_character.sh'
-
-      - name: Combat tests
-        id: combat_tests
-        run: docker exec test-server /bin/bash -c './tools/ci/test_combat.sh'
-
-      - name: Stop server
+      - name: Stop container
         run: |
-          docker exec test-server /bin/bash -c './tools/ci/stop_server.sh'
           docker stop test-server
           docker rm test-server
 
@@ -316,12 +325,12 @@ jobs:
         run: |
           echo "## Startup Results" >> $GITHUB_STEP_SUMMARY
           found_issues=false
-          for log_file in ./*.log; do
+          for log_file in ./log/*.log; do
               if [[ -f "$log_file" && -s "$log_file" ]]; then
                   if grep -qi "warning\|error\|crash\|critical" "$log_file"; then
                       found_issues=true
                       log_name=$(basename "$log_file" .log | sed 's/.*/\u&/; s/-\(.\)/ \u\1/g')
-                      echo "### :warning: ${log_name} Checks Failed" >> $GITHUB_STEP_SUMMARY
+                      echo "### :x: ${log_name} Checks Failed" >> $GITHUB_STEP_SUMMARY
                       echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
                       grep -i "warning\|error\|crash\|critical" "$log_file" >> $GITHUB_STEP_SUMMARY
                       echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
@@ -330,15 +339,15 @@ jobs:
               fi
           done
           if [[ "$found_issues" == "false" ]]; then
-              if [[ "${{ steps.combat_tests.outcome }}" == "success" ]]; then
-                  echo ":heavy_check_mark: All checks passed." >> $GITHUB_STEP_SUMMARY
+              if [[ "${{ steps.tests.outcome }}" == "success" ]]; then
+                  echo "### :heavy_check_mark: All checks passed." >> $GITHUB_STEP_SUMMARY
               else
-                  echo ":x: Combat check failed, but no specific errors were found." >> $GITHUB_STEP_SUMMARY
+                  echo "### :x: Combat check failed, but no specific errors were found." >> $GITHUB_STEP_SUMMARY
                   echo "Check the logs of the 'Combat tests' step for details." >> $GITHUB_STEP_SUMMARY
                   found_issues=true
               fi
           fi
-          for log_file in ./*.log; do
+          for log_file in ./log/*.log; do
               if [[ -f "$log_file" && -s "$log_file" ]]; then
                   log_name=$(basename "$log_file" .log | sed 's/.*/\u&/; s/-\(.\)/ \u\1/g')
                   echo "### :sailboat: ${log_name}" >> $GITHUB_STEP_SUMMARY
@@ -350,7 +359,7 @@ jobs:
           done
           echo "issues_found=$found_issues" >> $GITHUB_OUTPUT
       - name: Fail Workflow if Checks Failed
-        if: ${{ steps.combat_tests.outcome == 'failure' || steps.summarize_checks.outputs.issues_found == 'true' }}
+        if: ${{ steps.tests.outcome == 'failure' || steps.summarize_checks.outputs.issues_found == 'true' }}
         run: |
           echo "Startup checks failed. See summary for details."
           exit 1
@@ -443,6 +452,7 @@ jobs:
 
   # https://github.com/actions/runner-images/blob/main/images/windows/Windows2025-Readme.md
   Build_Windows:
+    name: Build Windows
     needs: Sanity_Checks
     runs-on: windows-2025
     defaults:
@@ -486,6 +496,7 @@ jobs:
       - name: Configure CMake
         run: |
           cp -p build/xi_* . 2> /dev/null || true
+          rm CMakeCache.txt || true
           cmake -S . -B build \
             -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
             -DENABLE_TRACY=${{ matrix.build_type == 'Debug' && 'ON' || 'OFF' }}
@@ -505,10 +516,11 @@ jobs:
             build
             tracy.tar.gz
 
-  Full_Startup_Checks_Windows:
+  Startup_Checks_Windows:
+    name: Startup Checks
     runs-on: windows-2025
     needs: Build_Windows
-    if: ${{ !cancelled() }}
+    if: ${{ !cancelled() && needs.Build_Windows.result == 'success' }}
     defaults:
       run:
         shell: bash
@@ -548,11 +560,9 @@ jobs:
       - name: Install Python dependencies
         if: ${{ !steps.python-cache.outputs.cache-hit }}
         run: |
-          python -m venv .venv
+          python3 -m venv .venv
           source .venv/Scripts/activate
           python -m pip install -r ./tools/requirements.txt
-          echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
-          echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
 
       - name: Activate Python virtual environment
         run: |
@@ -563,8 +573,8 @@ jobs:
         run: |
           which python
           python --version
-          pip --version
-          pip list
+          python -m pip --version
+          python -m pip list
 
       # TODO: only do this if src modules changed.
       # - name: Enable modules
@@ -581,10 +591,57 @@ jobs:
         run: python ./tools/dbtool.py update
 
       - name: Startup checks
-        run: python ./tools/ci/startup_checks.py
+        id: tests
+        run: python -m tools.ci.startup_checks
+
+      - name: Summarize checks
+        id: summarize_checks
+        if: ${{ always() }}
+        run: |
+          echo "## Startup Results" >> $GITHUB_STEP_SUMMARY
+          found_issues=false
+          for log_file in ./log/*.log; do
+              if [[ -f "$log_file" && -s "$log_file" ]]; then
+                  if grep -qi "warning\|error\|crash\|critical" "$log_file"; then
+                      found_issues=true
+                      log_name=$(basename "$log_file" .log | sed 's/.*/\u&/; s/-\(.\)/ \u\1/g')
+                      echo "### :x: ${log_name} Tests Failed" >> $GITHUB_STEP_SUMMARY
+                      echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+                      grep -i "warning\|error\|crash\|critical" "$log_file" >> $GITHUB_STEP_SUMMARY
+                      echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+                      echo "" >> $GITHUB_STEP_SUMMARY
+                  fi
+              fi
+          done
+          if [[ "$found_issues" == "false" ]]; then
+              if [[ "${{ steps.tests.outcome }}" == "success" ]]; then
+                  echo "### :heavy_check_mark: All tests passed." >> $GITHUB_STEP_SUMMARY
+              else
+                  echo "### :x: Startup tests failed, but no specific errors were found." >> $GITHUB_STEP_SUMMARY
+                  echo "Check the logs of the 'Startup tests' step for details." >> $GITHUB_STEP_SUMMARY
+                  found_issues=true
+              fi
+          fi
+          for log_file in ./log/*.log; do
+              if [[ -f "$log_file" && -s "$log_file" ]]; then
+                  log_name=$(basename "$log_file" .log | sed 's/.*/\u&/; s/-\(.\)/ \u\1/g')
+                  echo "### :sailboat: ${log_name}" >> $GITHUB_STEP_SUMMARY
+                  echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+                  cat "$log_file" >> $GITHUB_STEP_SUMMARY
+                  echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+                  echo "" >> $GITHUB_STEP_SUMMARY
+              fi
+          done
+          echo "issues_found=$found_issues" >> $GITHUB_OUTPUT
+      - name: Fail Workflow if Checks Failed
+        if: ${{ steps.tests.outcome == 'failure' || steps.summarize_checks.outputs.issues_found == 'true' }}
+        run: |
+          echo "Startup checks failed. See summary for details."
+          exit 1
 
   # https://github.com/actions/runner-images/blob/main/images/macos/macos-15-Readme.md
   Build_MacOS:
+    name: Build MacOS
     needs: Sanity_Checks
     runs-on: macos-15
     steps:
